language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer install --dev

script:
  - "php vendor/bin/phpcs --standard=PSR2 --extensions=php src/ test/Ajgon -p"
  - "php vendor/bin/phpmd --suffixes php src,test/Ajgon text codesize,controversial,design,unusedcode,naming"
  - "php vendor/bin/phpcpd src test"
  - "phpunit --coverage-clover=coverage.clover"

after_script:
  - "wget https://scrutinizer-ci.com/ocular.phar"
  - "php ocular.phar code-coverage:upload --format=php-clover coverage.clover"
