language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer install --dev

script:
  - "php vendor/bin/phpcs --standard=PSR2 --extensions=php src/ -p"
  - "php vendor/bin/phpmd --suffixes php src/* text codesize,controversial,design,unusedcode,naming"
  - "php vendor/bin/phpcpd src"
  - "php vendor/bin/phpunit --coverage-text"
